### ISSUE TITLE
TON to Jetton swap not working

### ISSUE THREAD

**Issue by slyofzero** [ston-fi/sdk#4]
While following the code on the [TON to Jetton](https://docs.ston.fi/docs/developer-section/dev-guide/swap#proxy-ton-jetton) swap guide using proxy TON, I keep getting the error.

`Error occurred - Rate limit exceeded: 1 per 1 second`

The code I am testing only has the wallet address changed and nothing else.

**Comment by Mehonoshin** [comment]
Same here.
When I use api token for ton center, there is a different error though:

`const provider = new TonWeb.HttpProvider('https://toncenter.com/api/v2/jsonRPC', {apiKey: 'mycode'});`

```
/Users/mexx/.yarn/berry/cache/tonweb-npm-0.0.63-a335dbafcf-10c0.zip/node_modules/tonweb/src/providers/HttpProviderUtils.js:51
            const err = new Error('http provider parse response error')
                        ^
Error: http provider parse response error
    at Function.parseResponse (/Users/mexx/.yarn/berry/cache/tonweb-npm-0.0.63-a335dbafcf-10c0.zip/node_modules/tonweb/src/providers/HttpProviderUtils.js:51:25)
    at HttpProvider.call2 (/Users/mexx/.yarn/berry/cache/tonweb-npm-0.0.63-a335dbafcf-10c0.zip/node_modules/tonweb/src/providers/index.js:154:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async K.getPoolAddress (/Users/mexx/Projects/dex-calc/.yarn/unplugged/@ston-fi-sdk-virtual-30e990c32b/node_modules/@ston-fi/sdk/src/contracts/dex/router/RouterRevisionV1.ts:73:20)
    at async wt.getPool (/Users/mexx/Projects/dex-calc/.yarn/unplugged/@ston-fi-sdk-virtual-30e990c32b/node_modules/@ston-fi/sdk/src/contracts/dex/router/Router.ts:171:25) {

```

**Comment by pavel-rakhmanov** [comment]
TonWeb, by default, [uses toncenter API](https://github.com/toncenter/tonweb/tree/master?tab=readme-ov-file#api) with a rate limit of 1 request per second

You can obtain higher limits by:
- requesting an API key from [toncenter](https://toncenter.com/) with a 10 request per minute limit
- use open TON API instance, for example, from [ORBS](https://www.orbs.com/ton-access/)
- found a paid instance of TON API with suitable rate limits for your case
- selfhost an instance of TON API
